#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LOCK_FILE="$ROOT/core/Cargo.lock"
OUT_FILE="$ROOT/uiua-modules/uiua_primitive_defs.rs"

if [[ ! -f "$LOCK_FILE" ]]; then
  echo "Missing lock file: $LOCK_FILE" >&2
  exit 1
fi

VERSION="$(
  awk '
    $1 == "name" && $3 == "\"uiua_parser\"" { found = 1; next }
    found && $1 == "version" {
      gsub(/"/, "", $3)
      print $3
      exit
    }
  ' "$LOCK_FILE"
)"

if [[ -z "${VERSION:-}" ]]; then
  echo "Could not find uiua_parser version in $LOCK_FILE" >&2
  exit 1
fi

shopt -s nullglob
MATCHES=("$HOME"/.cargo/registry/src/*/"uiua_parser-$VERSION"/src/defs.rs)
shopt -u nullglob

if [[ ${#MATCHES[@]} -eq 0 ]]; then
  echo "Could not find local source for uiua_parser-$VERSION." >&2
  echo "Try: cargo fetch --manifest-path core/Cargo.toml" >&2
  exit 1
fi

SOURCE_FILE="${MATCHES[0]}"

{
  echo "// Synced from uiua_parser v$VERSION"
  echo "// Source: uiua_parser-$VERSION/src/defs.rs (cargo registry)"
  echo "// Generated by scripts/sync-uiua-primitive-defs.sh"
  echo
  cat "$SOURCE_FILE"
} >"$OUT_FILE"

echo "Updated $OUT_FILE"
