import { createSignal, createEffect } from 'solid-js'

// 1. Import directly from the local file generated by wasm-pack
// Note: The file name usually matches your crate name (core -> core.js or chaos_engine.js)
// Check src/pkg/ to see the exact filename.
import init, { run_algo } from './pkg/chaos_engine'

import logisticCode from '../uiua-modules/logistic.ua?raw'

function App() {
  const [r, setR] = createSignal(2.5)
  const [data, setData] = createSignal<number[]>([])

  createEffect(async () => {
    // Initialize the Wasm memory
    await init()
  })

  createEffect(() => {
    // Run the algo when R changes
    const result = run_algo(logisticCode, r(), 0.5)
    // Convert Float64Array to standard array if needed, or pass directly
    setData(Array.from(result))
  })

  return (
    <div class="p-4">
      <h1 class="text-2xl font-bold mb-4">Logistic Map Explorer</h1>
      <div class="flex gap-4 items-center mb-4">
        <label>R = {r().toFixed(2)}</label>
        <input
          type="range"
          min="0"
          max="4"
          step="0.01"
          value={r()}
          onInput={(e) => setR(parseFloat(e.currentTarget.value))}
          class="w-64"
        />
      </div>

      {/* Placeholder for where we will put the Canvas */}
      <pre class="bg-gray-100 p-2 rounded max-h-40 overflow-auto">
        {JSON.stringify(data().slice(0, 10), null, 2)}
        ...
      </pre>
    </div>
  )
}

export default App
