import { createSignal, createEffect, onMount, Show } from 'solid-js'
import katex from 'katex'
import 'katex/dist/katex.min.css'

// 1. Import directly from the local file generated by wasm-pack
// Note: The file name usually matches your crate name (core -> core.js or chaos_engine.js)
// Check src/pkg/ to see the exact filename.
import init, { run_algo } from './pkg/chaos_engine'

import logisticCode from '../uiua-modules/logistic.ua?raw'

function App() {
  const [r, setR] = createSignal(2.5)
  const [data, setData] = createSignal<number[]>([])
  const [wasmReady, setWasmReady] = createSignal(false)

  init()
    .then(() => {
      console.log('WASM initialized successfully')
      setWasmReady(true)
    })
    .catch((e) => {
      console.error('WASM init failed:', e)
    })

  createEffect(() => {
    if (!wasmReady()) return
    const result = run_algo(logisticCode, r(), 0.5)
    setData(Array.from(result))
  })

  return (
    <Show
      when={wasmReady()}
      fallback={
        <div class="p-4 flex items-center gap-2">
          <div class="animate-spin h-5 w-5 border-2 border-gray-500 border-t-transparent rounded-full" />
          <span>Loading WASM...</span>
        </div>
      }
    >
      <div class="p-4">
        <h1 class="text-2xl font-bold mb-4">Logistic Map Explorer</h1>
        <div class="flex gap-4 items-center mb-4">
          <span innerHTML={katex.renderToString('x_{n+1} = rx_n(1-x_n)')} />

          <label>R = {r().toFixed(2)}</label>
          <input
            type="range"
            min="0"
            max="4"
            step="0.01"
            value={r()}
            onInput={(e) => setR(parseFloat(e.currentTarget.value))}
            class="w-64"
          />
        </div>

        {/* Placeholder for where we will put the Canvas */}
        <pre class="bg-gray-100 p-2 rounded max-h-40 overflow-auto">
          {JSON.stringify(data().slice(0, 10), null, 2)}
          ...
        </pre>
      </div>
    </Show>
  )
}

export default App
